# Generated by Django 5.1.2 on 2025-07-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeoffrequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='timeoffrequest',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=1),
        ),
    ]
